### ISSUE TITLE
Landing page: youtube video previews are stretched

### ISSUE THREAD

**Issue by dholbach** [fluxcd/website#1056]
![Bildschirmfoto von 2022-07-26 16-24-08](https://user-images.githubusercontent.com/1346979/181030916-20649e9a-8d48-4d17-9506-a7c28119099f.png)

**Comment by Santosh1176** [comment]
@dholbach Here's a mockup. Do you have any specific size in mind?

![flux-resource1](https://user-images.githubusercontent.com/91916466/181067809-eee92053-64a2-4d53-876f-0f84b141c74e.png)

**Comment by dholbach** [comment]
That looks great. About the size: I don't know - anything that's similar to what we've got, just in the right proportions?

**Comment by Santosh1176** [comment]
This is with 16:9 aspect ratio,  
![youtube-16-9](https://user-images.githubusercontent.com/91916466/181591815-4ceab586-b355-48ac-a880-b3e13016548e.png)

**Comment by dholbach** [comment]
Super. @staceypotter What do you think?

**Comment by Santosh1176** [comment]
Hey, @dholbach @staceypotter should I raise a PR with these settings?

**Comment by dholbach** [comment]
Yes that would be great
