### ISSUE TITLE
Kustomization doc typo

### ISSUE THREAD

**Issue by jhoval** [fluxcd/website#1058]
In the following page https://fluxcd.io/docs/components/kustomize/kustomization/ , you can see that below the Example,  the last bullet point says:

> When the Git revision changes, the manifests are reconciled automatically. If previously applied objects are missing from the current revision, these objects are deleted from the cluster when `spec.pune` is enabled.

I believe it should be **spec.prune**

![Screenshot 2022-07-27 at 12 43 57](https://user-images.githubusercontent.com/8077357/181228454-86ed84f2-71d1-45e1-a948-aa859dc54229.png)

**Comment by dholbach** [comment]
Thanks for reporting. The issue was resolved in https://github.com/fluxcd/kustomize-controller/pull/700 and will be fixed on the website once the next `kustomize-controller` release happens.
