### ISSUE TITLE
Color scheme doesnt match our actual branding colors

### ISSUE THREAD

**Issue by alisondy** [fluxcd/website#109]
making a a note of this

The colors we use in our website don't match the ones in our branding

```style.sass
// Flux color palette
$flux-darkest-blue: #3570e3
$flux-dark-blue: #2a7de3
$flux-lighter-blue: #1b8de2
$flux-light-blue: #0096e1
$flux-black: #1a1a1a
...
$primary: $flux-dark-blue
$secondary: $flux-light-blue
$dark: $flux-black

```

![Screen Shot 2021-03-19 at 10 03 58](https://user-images.githubusercontent.com/19580905/111763789-6ec9eb80-889a-11eb-95d8-a5885a5a25fc.png)

from https://branding.cncf.io/projects/flux/

**Comment by dholbach** [comment]
More colour feedback:
- "I do not really like the blue action button in the top hero, but that may be personal preference"
- "I played a bit with the background color of the videos / resources and wonder if we should give it the same color as the menu #1a1a1a"
- "grey should be less depressing"
- "hover link colour"
- "re-use flux blue for 'gitops toolkit""
- "look into alert colour in https://deploy-preview-130--fluxcd.netlify.app/docs/migration/flux-v1-migration/ - use boxes?"


@alisondy suggests (https://github.com/fluxcd/website/pull/130#issuecomment-824937347)
> Grey as #2f2f2f
> GitOps toolkit box, Other Flux Projects , same as top, fingertips #3d6ddd
> Flagger box, as green on flagger site #3eaf7c
> Community use Grey #2f2f2f
> Resources use Grey #2f2f2f

**Comment by dholbach** [comment]
@alisondy was this part of the branch you were working on?

**Comment by dholbach** [comment]
More colour feedback: 
- in the notes boxes, the code blocks have the same font colour as links
- the code blocks background could be greyish like we had in mkdocs, right now the contrast is huge

**Comment by dholbach** [comment]
#322 should have fixed a lot of the issues mentioned in here. AFAICS it's only my last comment that needs addressing.

If you have additional colour feedback, please speak up.

**Comment by dholbach** [comment]
It appears all the issues have been fixed, please reopen if that's not the case.

Thanks @juozasg !
