### ISSUE TITLE
Add GitOps Days talks

### ISSUE THREAD

**Issue by dholbach** [fluxcd/website#1101]
Add GitOps Days talks to https://fluxcd.io/resources

**Comment by dholbach** [comment]
cc @VanessaWeaveworksK8S

**Comment by VanessaWeaveworksK8S** [comment]
> Started will continue

**Comment by staceypotter** [comment]
> > Started will continue

@VanessaWeaveworksK8S What do you think about starting with the [GitOps Days 2022 Playlist](https://www.youtube.com/playlist?list=PL9lTuCFNLaD0NVkR17tno4X6BkxsbZZfr) first and then listing the individual sessions in chronological order (newest to oldest) below that? Thanks for getting this started!

**Comment by dholbach** [comment]
Is this resolved now?
