### ISSUE TITLE
Move Flux docs to /flux

### ISSUE THREAD

**Issue by dholbach** [fluxcd/website#1107]
@stefanprodan had the [idea](https://cloud-native.slack.com/archives/C01JR4YUG4B/p1661846782538519) of bringing us (long-term) to a 

`fluxcd.io / <project> / <version> / <document>`

structure.

A first step would be to move to these URL categories:

- fluxcd.io/flux
- fluxcd.io/flagger
- fluxcd.io/legacy

This would mean to move Flux docs under `/flux` and add redirects.

Thoughts?

**Comment by pjbgf** [comment]
+1 on the new approach, it sounds reasonable and easier to structure our docs going forward.
