### ISSUE TITLE
Finish break-up of core concepts doc

### ISSUE THREAD

**Issue by dholbach** [fluxcd/website#111]
@alisondy started work on this in #110 - looking good already!

**Comment by dholbach** [comment]
@alisondy Shall we push this back until #116 is done? So we can have the global redirect working first?

**Comment by dholbach** [comment]
https://github.com/alisondy/website/commit/a4b9a886dc404aa122e3d18c7acc8f4c1a26ddb3#diff-2d935a691066f5dc5402b97a3f970470419ae53a80bedf380793d96adb5c814e

Maybe get this into `f/flux2` first?

**Comment by alisondy** [comment]
Sounds like a good idea 👍

**Comment by kingdonb** [comment]
A PR was merged in #141, does that complete this issue?

**Comment by dholbach** [comment]
No, it's not right now there's only `./docs/concepts.md` - the idea was to break this up into various docs, cf https://github.com/alisondy/website/commit/a4b9a886dc404aa122e3d18c7acc8f4c1a26ddb3#diff-2d935a691066f5dc5402b97a3f970470419ae53a80bedf380793d96adb5c814e

**Comment by Neilblaze** [comment]
@dholbach can you please assign this to me? :)
