### ISSUE TITLE
Docs drop-down missing on mobile

### ISSUE THREAD

**Issue by dholbach** [fluxcd/website#1126]
Needs to be fixed in navbar

**Comment by dholbach** [comment]
![Screenshot_20220901-154320.png](https://user-images.githubusercontent.com/1346979/187929484-2ff81d7e-31f0-4559-b35d-f04c5c63acda.png)

**Comment by Santosh1176** [comment]
This looks good locally:
![local-mobile](https://user-images.githubusercontent.com/91916466/188265128-098eed93-d4cd-497b-8683-2e9695435922.png)
But the issue exists on the deployed site:
![deployed-mobile](https://user-images.githubusercontent.com/91916466/188265147-3f407ea3-bd32-4d53-9b9f-df446e1a60dd.png)
