### ISSUE TITLE
Complete landing page on new site

### ISSUE THREAD

**Issue by dholbach** [fluxcd/website#114]
Re: #110 

We still have a couple of blocks we want to add to the main page from fluxcd.io - let's see how we can add them to the site using `docsy` most easily.

**Comment by dholbach** [comment]
Most importantly re-add @hiddeco 's pretty terminal thingy

**Comment by dholbach** [comment]
I'm slowly bringing back the individual sections on the landing page. Because this is essentially a move from bulma to bootstrap and a change to a more shortcode-block-y docsy kind of a thinking some of this looks clunky and aesthetically not very pleasant (yet).

@alisondy @bia @hiddeco You might all have input, advice or fixes. :rotating_light: 

I'm not the best at CSS things, so for now I'll just focus to bring the content back first.

**Comment by dholbach** [comment]
https://deploy-preview-110--fluxcd.netlify.app/ has a preview.

**Comment by bia** [comment]
Nice work!

Could the grey background of 'Other Flux projects' be changed to match the footer `#403f4c`

The top nav bar also changes to a different colour when I scroll about 25% down the page, you can't see the logo well if it is not black : 
<img width="282" alt="Screenshot 2021-03-23 at 13 48 20" src="https://user-images.githubusercontent.com/92439/112148670-706b1a80-8bde-11eb-8897-1ffac8a4d9cf.png">

**Comment by dholbach** [comment]
All content (apart from the ascii terminal) is on.
