### ISSUE TITLE
List of what Flux supports natively?

### ISSUE THREAD

**Issue by mewzherder** [fluxcd/website#1155]
not sure where would be the right place, but perhaps https://fluxcd.io/ecosystem/ would be the right place for a section of what Flux supports natively? eg. Helm, HashiCorp Vault, etc.?

**Comment by dholbach** [comment]
Stefan had doubts about adding all of this to the Ecosystem section.

In the end we moved to: https://fluxcd.io/flux/#flux-works-well-with
