### ISSUE TITLE
ecosystem: Datadog integration for flux2

### ISSUE THREAD

**Issue by dholbach** [fluxcd/website#1168]
Hello just to inform you that Blablacar developed a [Datadog integration for flux2 ](https://github.com/DataDog/integrations-extras/tree/master/fluxcd)
This enable to scrape metrics from datadog agent.

_Originally posted by @melchiormoulin in https://github.com/fluxcd/flux2/discussions/3157_

→ we could add the integration to https://fluxcd.io/ecosystem/#integrations

**Comment by Santosh1176** [comment]
Hey @dholbach can I work on this?

**Comment by dholbach** [comment]
Sure that'd be great!

**Comment by dholbach** [comment]
This was resolved in #1183
