### ISSUE TITLE
Algolia: de-prioritise generated API docs

### ISSUE THREAD

**Issue by dholbach** [fluxcd/website#1189]
Another issue is that Angolia prioritises the generated API docs instead of the one written for end-users, which is less than ideal.

_Originally posted by @stefanprodan in https://github.com/fluxcd/website/issues/1185#issuecomment-1275827841_

**Comment by dholbach** [comment]
https://www.algolia.com/doc/guides/managing-results/must-do/custom-ranking/how-to/boost-or-penalize-some-records/ could be relevant here.

**Comment by dholbach** [comment]
I just followed https://docsearch.algolia.com/docs/record-extractor/#boost-search-results-with-pagerank and added this `pageRank` rule:

@stefanprodan LMK if that worked. 

```json
    {
      indexName: "fluxcd",
      pathsToMatch: ["https://fluxcd.io/flux/components/**/api/"],
      recordExtractor: ({ $, helpers }) => {
        return helpers.docsearch({
          recordProps: {
            lvl1: "main h1",
            content: "main p, main li",
            lvl0: {
              selectors: "",
              defaultValue: "Documentation",
            },
            lvl2: "main h2",
            lvl3: "main h3",
            lvl4: "main h4",
            lvl5: "main h5",
            pageRank: -1,
          },
          indexHeadings: true,
        });
      },
    },
```

**Comment by stefanprodan** [comment]
Works great now, thanks @dholbach 🏅

**Comment by dholbach** [comment]
Looks like it's working better now. Please reopen if we need more fine-tuning.
