### ISSUE TITLE
Add KubeCon 2022 NA videos

### ISSUE THREAD

**Issue by dholbach** [fluxcd/website#1239]
Add KubeCon 2022 NA videos to https://github.com/fluxcd/website/blob/main/content/en/resources.yaml

cc @staceypotter and @vanessaabankwah

**Comment by dholbach** [comment]
While we are at it, we should add the videos to this playlist as well: https://www.youtube.com/playlist?list=PLwjBY07V76p4qczDNgH08GQVdzgcwXpdY

**Comment by vanessaabankwah** [comment]
> While we are at it, we should add the videos to this playlist as well: https://www.youtube.com/playlist?list=PLwjBY07V76p4qczDNgH08GQVdzgcwXpdY

ill work on it

**Comment by dholbach** [comment]
https://www.youtube.com/c/cloudnativefdn/videos

**Comment by dholbach** [comment]
@vanessaabankwah confirmed: we're done.
