### ISSUE TITLE
Enable Google Analytics 4 (GA4)

### ISSUE THREAD

**Issue by chalin** [fluxcd/website#1270]
This issue is part of a CNCF-wide effort to set up or upgrade project websites to GA4 since **Google has deprecated Universal Analytics** (UA). For more details, see:

- https://github.com/cncf/techdocs/issues/108, including reference to a suggested [migration process](https://github.com/cncf/techdocs/blob/main/docs/analytics.md#migrating-to-google-analytics-4), which we've used to [migrate a few CNCF projects](https://docs.google.com/spreadsheets/d/1Mx4LhdI2Un-rvGMI73SlHxQH9D2HABAJclMB3dd6lnA) already.

### Questions

- I'm not seeing any analytics for the website. Can one of the maintainers confirm that that is the case?
- There are a number of alternatives for setting up GA4. The simplest setup is through [Netlify snippet injection]. I'm glad to setup GA4 if you'd like, just as I've done for other CNCF project websites. I'll need access to your Netlify account for that (I'm not seeing fluxcd under the CNCF Netlify accounts). If you'd prefer GA setup using Hugo config + layouts, I can do that too.

/cc @caniszczyk @nate-double-u

[Netlify snippet injection]: https://docs.netlify.com/site-deploys/post-processing/snippet-injection/

**Comment by dholbach** [comment]
We don't use analytics right now.

**Comment by dholbach** [comment]
Probably safe to close for now.

**Comment by chalin** [comment]
@dholbach - I'm back from vacation. Can you reopen this issue? I'll submit a PR in the new year to enable GA4, depending on how you'd like that setup (my suggesting is to use Netlify snippet injection of your using Netlify for hosting). Thanks!

**Comment by stefanprodan** [comment]
@chalin we don’t want to annoy Flux users with GDPR popups so we don’t track them with cookies. Personally I don’t find it acceptable to use Google Analytics for OSS projects, why is CNCF pushing this?
