### ISSUE TITLE
Create adopters page for Flux 2 users 

### ISSUE THREAD

**Issue by dholbach** [fluxcd/website#129]
Create adopters page for Flux 2 users.

**Comment by dholbach** [comment]
It'd be great if we could have a `ADOPTERS.yml` (it could live in `f/flux2` as well?) where folks can add company name and url to logo and we auto-generate the page? Not sure if that's too much effort though...

**Comment by scottrigby** [comment]
💯 We could set up an issue template for this as well

**Comment by dholbach** [comment]
> 100 We could set up an issue template for this as well

Ah, so instead of people adding an entry to the yaml, they'd file an issue for this? I think I'd prefer the PR approach, as it'll be easier to spot who added which entry?

**Comment by scottrigby** [comment]
@dholbach Yep agreed, ultimately this is what I meant 😸  https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository

**Comment by dholbach** [comment]
ah yes!
