### ISSUE TITLE
Trim landing page

### ISSUE THREAD

**Issue by dholbach** [fluxcd/website#1327]
Ideas:

- "the gitops at your fingertips" section overlaps heavily with "flux in short"~~
- ~~Remove "other flux projects"~~
- ~~show only 3 resources, and link to the resources page instead~~
- ~~make contributors section smaller~~

**Comment by stefanprodan** [comment]
The feedback I got from several people who are not into cloud-native is that our homepage is cluttered  and the info is duplicated. I think we should trim down the things we show on the home page.

**Comment by dholbach** [comment]
What's left to be done, is to merge the "gitops ar your fingertips" and "flux in short" sections. Help would be appreciated for this.

**Comment by dholbach** [comment]
Current sections are

---


🤝 Flux provides GitOps for both apps and infrastructure
Flux and [Flagger](https://github.com/fluxcd/flagger) deploy apps with canaries, feature flags, and A/B rollouts. Flux can also manage any Kubernetes resource. Infrastructure and workload dependency management is built in.

🤖 Just push to Git and Flux does the rest
Flux enables application deployment (CD) and (with the help of [Flagger](https://github.com/fluxcd/flagger)) progressive delivery (PD) through automatic reconciliation. Flux can even push back to Git for you with automated container image updates to Git (image scanning and patching).

🔩 Flux works with your existing tools
Flux works with your Git providers (GitHub, GitLab, Bitbucket, can even use s3-compatible buckets as a source), all major container registries, fully integrates [with OCI](https://fluxcd.io/flux/cheatsheets/oci-artifacts) and all CI workflow providers.

🔒 Flux is designed with security in mind
Pull vs. Push, least amount of privileges, adherence to Kubernetes security policies and tight integration with security tools and best-practices. Read more about [our security considerations](https://fluxcd.io/flux/security).

☸️ Flux works with any Kubernetes and all common Kubernetes tooling
Kustomize, Helm, RBAC, and policy-driven validation (OPA, Kyverno, admission controllers) so it simply falls into place.

🤹 Flux does Multi-Tenancy (and “Multi-everything”)
Flux uses true Kubernetes RBAC via impersonation and supports multiple Git repositories. Multi-cluster infrastructure and apps work out of the box with Cluster API: Flux can use one Kubernetes cluster to manage apps in either the same or other clusters, spin up additional clusters themselves, and manage clusters including lifecycle and fleets.

✨ Dashboards love Flux
No matter if you use one of [the Flux UIs](https://fluxcd.io/ecosystem/#flux-uis--guis) or a hosted cloud offering from your cloud vendor, Flux has a thriving ecosystem of integrations and products built on top of it and all have great dashboards for you.

📞 Flux alerts and notifies
Flux provides health assessments, alerting to external systems, and external events handling. Just “git push”, and get notified on Slack and [other chat systems](https://fluxcd.io/flux/components/notification/provider/).

👍 Users trust Flux
Flux is a CNCF Graduated project and was categorised as "Adopt" on the [CNCF CI/CD Tech Radar](https://radar.cncf.io/2020-06-continuous-delivery) (alongside Helm).

💖 Flux has a lovely community that is very easy to work with!
We welcome contributors of any kind. The components of Flux are on Kubernetes core controller-runtime, so anyone can contribute and its functionality can be extended very easily.

---


**Declarative**
Describe the entire desired state of your system in [Git](https://git-scm.com/). This includes apps, configuration, dashboards, monitoring, and everything else.

**Automated**
Use [YAML](https://yaml.org/) to enforce conformance to the declared system. You don’t need to run [kubectl](https://kubectl.docs.kubernetes.io/) because all changes are synced automatically.

**Auditable**
Everything is controlled through pull requests. Your Git history provides a sequence of transactions, allowing you to recover state from any snapshot.

**Designed for Kubernetes**
Declaratively configurable using Custom Resources, state reports in the [object’s status](https://kubernetes.io/docs/concepts/overview/working-with-objects/kubernetes-objects/#object-spec-and-status) and via [Kubernetes Events](https://kubernetes.io/docs/tasks/debug-application-cluster/debug-application-introspection/), and integrations with Kubernetes RBAC

**Out-of-the-box integrations**
Support for e.g. [Kustomize](https://kustomize.io/), [Helm](https://helm.sh/); GitHub, GitLab, Harbor and custom webhooks; notifications to most team communication platforms; and many more.

**Extensible**
Easily create a continuous delivery solution with only the components you need, or use the [GitOps Toolkit](https://fluxcd.io/flux/components/) to extend Flux.
Use [YAML](https://yaml.org/) to enforce conformance to the declared system. You don’t need to run [kubectl](https://kubectl.docs.kubernetes.io/) because all changes are synced automatically.
