### ISSUE TITLE
Commercial support page has a logo that doesnt render

### ISSUE THREAD

**Issue by jmymy** [fluxcd/website#1328]
![Screenshot 2022-12-14 at 10 32 52 AM](https://user-images.githubusercontent.com/13502328/207573374-d3ee39b8-9201-465c-b38d-7d7e586c5a43.png)
![Screenshot 2022-12-14 at 10 39 40 AM](https://user-images.githubusercontent.com/13502328/207573489-c9d4bf0c-d80e-4bfb-ac85-c12d4ebf8790.png)

looks like the image is present, just renders to a 0x0 px

**Comment by dholbach** [comment]
Fixed in #1329
