### ISSUE TITLE
A few broken links 

### ISSUE THREAD

**Issue by SafeEHA** [fluxcd/website#1476]
In the Blog section on [this](https://fluxcd.io/flux/guides/monitoring/) page, I noticed the links to the flux dashboards [http://localhost:3000/d/flux-control-plane](http://localhost:3000/d/flux-control-plane/flux-control-plane), [http://localhost:3000/d/flux-cluster](http://localhost:3000/d/flux-cluster/flux-cluster-stats) and [http://localhost:3000/d/flux-logs](http://localhost:3000/d/flux-logs/flux-logs) are all throwing a timeout error

I also found that on [this](https://fluxcd.io/adopters/) page, [https://identinet.id/](https://identinet.id/)  and on [this](https://fluxcd.io/blog/2022/04/march-update/), [this](http://kustomize.toolkit.fluxcd.io/ssa) are both throwing a typo error

Please I would like to fix these as soon as possible

cc @kingdonb @dholbach

**Comment by kingdonb** [comment]
Hello @SafeEHA ! Thanks for taking a look at this!

> `kubectl -n monitoring port-forward svc/kube-prometheus-stack-grafana 3000:80`
From the example guide, kube-prometheus-stack-grafana's port 80 is forwarded to localhost on port 3000 here.

If you are following the guide, then the link will not be broken.

As far as `identinet.id` – that does look to be a typo, it seems that the company can be found at `identinet.io` – that one has the same logo, anyway. Thanks for flagging this!

**Comment by SafeEHA** [comment]
Thanks for clearing that up @kingdonb I'm happy to help anytime
There are some more links throwing errors, I would be happy to look through them to make sure they're not a blocker for new users or old ones

**Comment by kingdonb** [comment]
Looks like the one issue regarding `identinet.io` has been resolved 👍 

If you have any PRs where you think you've identified a broken link, please send them and we'll review each one. It's better to send these updates one at a time than in bulk, that way we can review each one more critically and close if it's a red herring.

From the list you mentioned before, I think that identinet was the only one that looked troublesome.

I'll close this now, but if there are other changes you'd like to make, please do send as a PR!
