### ISSUE TITLE
Providers - variable "sigHdr" 

### ISSUE THREAD

**Issue by michaelsatish** [fluxcd/website#1559]
The example provided for implementing HMAC verification does not have the variable "sigHdr" declared or passed to the "verifySignature" function. 
https://fluxcd.io/flux/components/notification/provider/#hmac-verification-example

```go
default:
    return fmt.Errorf("unsupported signature algorithm %q", sigHdr[0])
```

```go
if sum != sig[0] {
    return fmt.Errorf("HMACs do not match: %#v != %#v", sum, sigHdr[0])
}
```

Is this a typo? I am new to the go language.

**Comment by kingdonb** [comment]
It looks like a typo:

```go
        if sum != sig[0] {
		return fmt.Errorf("HMACs do not match: %#v != %#v", sum, sigHdr[0])
	}
```

`sig[0]` should be used throughout, where it says `sigHdr[0]` it should say `sig[0]` - it looks pretty clear at least, since the comparison uses `sig[0]` that's what the error should represent as well.

Good find! Do you want to submit a PR fixing this, and we'll take it in for review?

**Comment by michaelsatish** [comment]
@kingdonb I will submit a PR.

**Comment by michaelsatish** [comment]
Hi @kingdonb 

I see the script `./hack/import-flux2-assets.sh` pulling the right provider doc. 

https://github.com/fluxcd/website/blob/dafc8d8876a3841e225594ac5d0c67166930033e/hack/import-flux2-assets.sh#L156C82-L156C98

The notification controller release `v1.0.0-rc.4` has the typo

https://github.com/fluxcd/notification-controller/blob/v1.0.0-rc.4/docs/spec/v1beta2/providers.md#hmac-verification-example

The typo is fixed in release `1.0.0`

https://github.com/fluxcd/notification-controller/blob/v1.0.0/docs/spec/v1beta2/providers.md#hmac-verification-example

I think the website just needs a rebuild.

**Comment by michaelsatish** [comment]
@kingdonb 

Going through the provider doc in version `1.0.0`, I do see another issue.

https://github.com/fluxcd/notification-controller/blob/v1.0.0/docs/spec/v1beta2/providers.md#generic-webhook-with-hmac

The key parameter is of type byte array.
```go
func verifySignature(signature string, payload, key []byte) error
```
In the `handleRequest` function, a key of type string is passed.

```go
key := "<token>"
if err := verifySignature(r.Header.Get("X-Signature"), body, key); err != nil {
    http.Error(w, fmt.Sprintf("failed to verify HMAC signature: %s", err.Error()), http.StatusBadRequest)
    return
}
```

**Comment by kingdonb** [comment]
I'm not sure about the convention here, is it safe to directly coerce a string into a byte slice

Can you add the conversion, IDK if it's `[]byte(` or what, I am only sort-of a go programmer.

It will be of tremendous help if you can post a link on your PR to some published package or somewhere that we can confirm you've tested it and it works for all intents, and we can scrutinize any differences with what is documented to help decide if there's a bug in the docs or not.

So while I'm happy to provide reviews and I'm going to be somewhat limited in what I can do myself with respect to reviewing Go for correctness and idiomaticness, but I certainly know how to run a compiler and tests, so if you can show me a package where you're using this that would be ideal, and/or tell for sure that it works somewhere even if you cannot publish, it's going to help with the mergeability.

I do not want to merge any half corrections, let's be sure that it works 👍

**Comment by kingdonb** [comment]
Checking the git blame on that doc, it looks like most of the function was written about 7 months ago in two PRs, and one change was merged 3 weeks ago fixing this issue.

I see the PR that already fixed this issue:

* https://github.com/fluxcd/notification-controller/pull/557

Thank you for reporting this issue, I only saw the second of your comments, and it is a problem if the dependencies from the website aren't rebuilding, or they aren't going to the website. I'm not sure how this happens, we will need to look into it.

**Comment by kingdonb** [comment]
I'm just checking on the issue, I am looking at https://fluxcd.io/flux/components/notification/provider/#hmac-verification-example and although fluxcd/notification-controller#557 has been merged, I don't see the change:

```
s/sigHdr[0]/sig[0]/g
```

that I would expect to see on the public-facing URL. That's odd, I don't have more information just now, only wanted to let you know, I haven't lost track of this...

Can you give me an idea if you're still tracking this, is everything you've identified as an issue solved in the main branch, or are there fixes still needed... and has any of this made it to the website yet, or are we thinking this is stuck?

I haven't done a deep dive into the website to try to understand if something is broken just yet, but it might be that the changes in notification controller haven't been tagged in a release yet. I don't know how this part of the website works yet...

**Comment by michaelsatish** [comment]
@kingdonb I see the fix from https://github.com/fluxcd/notification-controller/pull/557 on the public facing URL.
 
https://fluxcd.io/flux/components/notification/provider/#hmac-verification-example

```go
default:
    return fmt.Errorf("unsupported signature algorithm %q", sig[0])
```

```go
if sum != sig[1] {
    return fmt.Errorf("HMACs do not match: %#v != %#v", sum, sig[1])
}

**Comment by kingdonb** [comment]
@michaelsatish We saw this issue of the docs fixed here:

* https://github.com/fluxcd/website/pull/1571

Thank you for mentioning it again, I had lost track of this conversation and wanted to make sure and circle back to let you know the issue causing the docs to not get the latest updates was resolved!

I think we can close this now. 🙇
