### ISSUE TITLE
import-flux2-docs.sh: 'sort -V' does not do proper semver

### ISSUE THREAD

**Issue by dholbach** [fluxcd/website#156]
This will give unexpected results with prereleases, see:

```console
$ printf '%s\n' v1.2.0 v1.1.0 v1.2.0-alpha v1.3.0-test v2.0.0-alpha | sort -V | tail -n1
v2.0.0-alpha
```

_Originally posted by @hiddeco in https://github.com/fluxcd/website/pull/155#discussion_r620353986_

**Comment by dholbach** [comment]
So I looked at a couple of tools and libraries out there... e.g. https://github.com/ccrisan/semver-sort complains about the `v` and pays no attention to `-alpha`, `-test` or whatever. 

Anyone got a good tool or library to solve this?

**Comment by sonbui00** [comment]
Don't see this issue now. we can close @kingdonb
