### ISSUE TITLE
Pull in https://github.com/fluxcd/flux2/blob/main/install/flux.sh

### ISSUE THREAD

**Issue by dholbach** [fluxcd/website#158]
https://toolkit.fluxcd.io/install.sh is currently where folks get their `flux` binary from.

Let's make sure we provide this as well - https://github.com/fluxcd/flux2/blob/main/install/flux.sh is the source.

**Comment by hiddeco** [comment]
This would also require a change in the documentation to advertise the new URL.

**Comment by dholbach** [comment]
Yes....

1. Provide script
2. Make sure redirects work
3. Update docs to new URLs

🙈
