### ISSUE TITLE
flux completion bash - : bad option: -t

### ISSUE THREAD

**Issue by cforce** [fluxcd/website#1688]
I followed the docs and ran into the below issue

➜ curl -s https://fluxcd.io/install.sh | sudo bash
[INFO]  Downloading metadata https://api.github.com/repos/fluxcd/flux2/releases/latest
[INFO]  Using 2.1.2 as release
[INFO]  Downloading hash https://github.com/fluxcd/flux2/releases/download/v2.1.2/flux_2.1.2_checksums.txt
[INFO]  Downloading binary https://github.com/fluxcd/flux2/releases/download/v2.1.2/flux_2.1.2_linux_amd64.tar.gz
[INFO]  Verifying binary download
[INFO]  Installing flux to /usr/local/bin/flux

~ took 4.5s
➜ . <(flux completion bash)
/proc/self/fd/11:type:12106: bad option: -t

~
➜

**Comment by makkes** [comment]
You need to place a space between the dot and the `<`:
```
$ . <(flux completion bash)
```
