### ISSUE TITLE
docs: webhook link 404

### ISSUE THREAD

**Issue by jack1902** [fluxcd/website#1691]
### Describe the bug

Upon clicking on Receiver CRD Docs on https://fluxcd.io/flux/guides/image-update/#trigger-image-updates-with-webhooks you get a 404

![Screenshot 2023-10-16 at 17 08 19](https://github.com/fluxcd/flux2/assets/39212456/8d70686c-cf23-4c85-87d7-0417fe58de3a)

### Steps to reproduce

1. Visit https://fluxcd.io/flux/guides/image-update/#trigger-image-updates-with-webhooks
2. Click the `other receivers` piece for the CRD spec

### Expected behavior

Believe i should be presented with https://fluxcd.io/flux/components/notification/receivers/

The URL has `guides/` removed:

- works: https://fluxcd.io/flux/components/notification/receivers/
- fails:    https://fluxcd.io/flux/guides/components/notification/receiver

### OS / Distro

N/A

### Flux version

N/A

### Flux check

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kingdonb** [comment]
This was fixed in #1735
