### ISSUE TITLE
Add tab(s) shortcodes

### ISSUE THREAD

**Issue by dholbach** [fluxcd/website#176]
The `tab` and `tabs` bits from https://github.com/tektoncd/website/tree/main/layouts/shortcodes would be nice to have, so we could do something like https://raw.githubusercontent.com/tektoncd/cli/main/docs/README.md

**Comment by dholbach** [comment]
Some of the CSS magic would be needed too.

**Comment by alisondy** [comment]
https://www.docsy.dev/docs/adding-content/shortcodes/#tabbed-panes

they're already built in

**Comment by dholbach** [comment]
@stefanprodan Where would you like to see this used? In https://fluxcd.io/docs/get-started/#install-the-flux-cli maybe?

**Comment by stefanprodan** [comment]
Lots of places, notification, install, secrets, etc everywhere we have multiple options to do the same thing.

**Comment by dholbach** [comment]
Looks like we'll need a newer version of docsy though.
