### ISSUE TITLE
tmp directory is 100% utilized in FluxCD. FluxCD Pod is evicted 

### ISSUE THREAD

**Issue by rajagopalrao** [fluxcd/website#1876]
When scheduling new workloads getting an out of space error:
failed to copy temp contents: write /tmp/fetch.751668774.tmp: no space left on device

**Comment by rajagopalrao** [comment]
FluxCD version is 2.2.3

**Comment by kingdonb** [comment]
Please take a look at the output of `flux stats -A` to see which resources are consuming the most.

https://fluxcd.io/flux/cmd/flux_stats/

Bottom line is Flux clones the repositories you tell it to, and if they are large, then they will consume a lot of space. We do not recommend using Flux to bootstrap in your monorepo, where source-controller will necessarily need to clone the entire repo full of unrelated artifacts just to access a small directory with a few kilobytes of YAML.

If Flux is not consuming many resources in the stats output, then the next place to look is on your nodes. How much space exactly is being consumed by tmp to result in pod eviction? If it's a very small amount, this could be a misconfiguration of the nodes, or it could be nodes that are filling up their disk.

The most likely culprit is needless cloning a git repo that is too big.

**Comment by kingdonb** [comment]
The fluxcd/website repo is not really the place for Flux debugging issues, please see [Community: Communication](https://fluxcd.io/community/#communication) for alternative ideas where you might find support, or [Support](https://fluxcd.io/support/)
