### ISSUE TITLE
Update the oci cheatsheet for notation

### ISSUE THREAD

**Issue by souleb** [fluxcd/website#1878]
Update the [OCI cheatsheet](https://fluxcd.io/flux/cheatsheets/oci-artifacts/#signing-and-verification) to show how to use `notation`.

This is a follow-up to https://github.com/fluxcd/source-controller/pull/1075.

**Comment by kingdonb** [comment]
Is there anything left that needs to be added to the OCI cheatsheet:

https://fluxcd.io/flux/cheatsheets/oci-artifacts/#notary-workflow-example
