### ISSUE TITLE
Audio walk-through option for the Terminal gif

### ISSUE THREAD

**Issue by mewzherder** [fluxcd/website#189]
@kingdonb just did a fantastic quick walk-through of Flux just by speaking while the Terminal gif was running. I think it would be helpful to record that and people could have the option to hear it as they're watching the gif. It might mean changing the gif to a video recording with a mute on/off option. This would be extra helpful for aural learners.

**Comment by hiddeco** [comment]
FYI: the terminal is not a gif nor a video, but an [asciinema](https://asciinema.org) recording.
