### ISSUE TITLE
Point to /f/community

### ISSUE THREAD

**Issue by dholbach** [fluxcd/website#19]
Once https://github.com/fluxcd/community/issues/6 is resolved, we should point to the README from the /f/community repository as a good way into the community.

**Comment by dholbach** [comment]
If this is about importing bits from various repos into the website, we might as well punt it to a later milestone.

**Comment by hiddeco** [comment]
Addressed part of "linking to community" by adjusting the menu, and moved the milestone for further changes.

**Comment by dholbach** [comment]
It'll be important to link to meeting information, events and get-involved kind of info very prominently.

If we fix fluxcd/community#6 and make it beautiful, can we pull that README in and e.g. make it fluxcd.io/community or /get-involved or some such?

**Comment by dholbach** [comment]
It might make sense to write /f/community/README.md like a very nice guide for somebody who's new to the community ... and link off to more detailed GH docs for the nitty gritty.

We'd need to 

1) rewrite README
2) add import script (maybe re-use parts of https://github.com/kubernetes-sigs/contributor-site/blob/master/hack/gen-content.sh?)
3) work on styling of "normal pages" on the site?

**Comment by dholbach** [comment]
CCing @scottrigby and @somtochiama

**Comment by dholbach** [comment]
Fixed by https://github.com/fluxcd/website/pull/74
