### ISSUE TITLE
Review search functionality

### ISSUE THREAD

**Issue by dholbach** [fluxcd/website#196]
Docsy gives us this: https://www.docsy.dev/docs/adding-content/navigation/#site-search-options

We should take a look and figure out what works best for us.

**Comment by stefanprodan** [comment]
Let's try algolia, Calico uses it, check it out: https://docs.projectcalico.org/about/about-calico

**Comment by dholbach** [comment]
I signed up for their services. I'll let you know once they replied.

**Comment by dholbach** [comment]
I got an email where they asked if I was maintainer of the site - let's see how the rest of the conversation goes... :crossed_fingers:
