### ISSUE TITLE
Git Repositories

### ISSUE THREAD

**Issue by theJaxon** [fluxcd/website#2093]
`master` branch name should be changed in the docs to `main` instead since this is the current convention used.

**Comment by kingdonb** [comment]
I'm all for inclusive language, and you are welcome to submit a PR if you like. But some repositories (including ones we've definitely referenced) still use a `master` branch so it's not as simple as a global grep/find/replace.

For those repos that may have published go modules, and other reasons, I think changing the default branch is not trivial.

**Comment by theJaxon** [comment]
@kingdonb Thanks for clarifying, I'll be closing the issue then.
