### ISSUE TITLE
Flux stuck after pgpmissconfiguration

### ISSUE THREAD

**Issue by Yaikava** [fluxcd/website#2109]
So I did a little mistake.

I was enabling pgp verification for commits, but miss-typed my secret name. Now I am stuck with flux not accepting any changes.

Any way to fix this?

Thanks

**Comment by stefanprodan** [comment]
If this is in the root GitRepository, then you need to run `flux uninstall` and then rerun `flux bootstrap`.

**Comment by Yaikava** [comment]
Worked
