### ISSUE TITLE
ARM note

### ISSUE THREAD

**Issue by aledegano** [fluxcd/website#220]
Hello!
It seems that the note about ARM architecture flag introduced in fluxcd/flux2#327 got lost (I guess docs have been moved to this repository from flux2?). If this was not intentional I'd be happy to open a PR to re-introduce the note.

Additionally `flux bootstrap --help` does not mention the `--arch` flag at all, so perhaps we could add it? (but I guess this is an issue for the flux2 repo?)

**Comment by stefanprodan** [comment]
There is no more need for `--arch`, see the docs: https://fluxcd.io/docs/guides/installation/#bootstrap

> The Flux component images are published to DockerHub and GitHub Container Registry as multi-arch container images with support for Linux amd64, arm64 and armv7 (e.g. 32bit Raspberry Pi) architectures.

**Comment by aledegano** [comment]
I realized after opening the issue that the flag was no longer necessary (and thus closed the issue).
Sorry for the noise!
