### ISSUE TITLE
prometheus and grafana: data is not persistent

### ISSUE THREAD

**Issue by rryter** [fluxcd/website#222]
I followed the guide https://fluxcd.io/docs/guides/monitoring and it does install Prometheus and Grafana but the data collected, as well as the dashboard configurations are not persited properly. It seems `flux reconcile`causes the data to be deleted.

What am I missing?

**Comment by rryter** [comment]
Wrong repo. Sorry

**Comment by stefanprodan** [comment]
> It seems flux reconcile causes the data to be deleted.

Are you saying that the Prometheus pods gets deleted after each reconciliation?

**Comment by stefanprodan** [comment]
> How can I make the changes persistent? Do I have to create my custom version of the monitoring manifests?

There are many ways to setup persistence, it can be done with Kubernetes persistent volumes or Prometheus remote write to Cortex or Thanos, or the AWS managed Prom, etc. It’s up to you to decide how to handle this based on your environment and budget.
