### ISSUE TITLE
how to contribute to flux docs guides

### ISSUE THREAD

**Issue by alisondy** [fluxcd/website#237]
Don't have information on how to contribute to the Flux docs, surfaced in the Flux docs.
This makes it hard for people unfamiliar with the website repo, to contribute to the docs.

Cover the following stories

* As a Flux Contributor I would like to know how to create a page on the flux docs
* As a Flux Contributor I would like to know what shortcodes I can use on the docs
* As a Flux contributor I would like to know what I can do to contribute to Flux Docs

Create the following guides
- Contribute to Flux docs
- How to add a page on the documentation
- Custom Hugo Shortcodes

Structured as so
contributing/
    _index.md # contribute to flux docs
    howto-adddocs.md # How to add a page on the documentation
    shortcodes.md # Custom Hugo Shortcodes

**Comment by dholbach** [comment]
We have a little background info in https://github.com/fluxcd/website/#readme but it doesn't answer the questions you have brought up yet.

**Comment by dholbach** [comment]
#262 built the structure or this, new guides will land here: https://fluxcd.io/docs/contributing/docs/
