### ISSUE TITLE
Style Guide for Docs

### ISSUE THREAD

**Issue by alisondy** [fluxcd/website#238]
Create a style guide for writing documentation

This will capture
> how we format code snippets
> the language we should be using

References
https://kubernetes.io/docs/contribute/style/style-guide/

**Comment by dholbach** [comment]
Overlap with #131 ? Or can #131 be closed now that we distinguish between content and style guides?

**Comment by alisondy** [comment]
#131 sounds like an umbrella that covers both #238 and #239

**Comment by dholbach** [comment]
Fixed by #393
