### ISSUE TITLE
Load terminal from the get-go

### ISSUE THREAD

**Issue by dholbach** [fluxcd/website#301]
Right now our page loads, then the terminal is loaded. https://tekton.dev/ doesn't seem to have this problem.

https://github.com/tektoncd/website/search?q=asciinema could be a good starting point.

**Comment by dholbach** [comment]
https://nixos.org/ might serve as an example.

**Comment by juozasg** [comment]
I believe that the only solution to increase load priority for asciinema.js is to load it with static <script> inclusion - currently we are appending it to <head> only when the client is widescreen.  So we either download 592kB on mobile or we wait for all the statically defined stuff to load first. Maybe we could use a preview image to load the terminal to avoid ugly layout reflows?

**Comment by stefanprodan** [comment]
>  Maybe we could use a preview image while loading the terminal to avoid unseemly layout reflows?

That would be great! 👍
