### ISSUE TITLE
List tools and integrations that work with Flux

### ISSUE THREAD

**Issue by dholbach** [fluxcd/website#302]
Not sure where to best place this, but we should list integrations and tools like 

- https://github.com/kaizentm/gitops-connector
- https://github.com/fidelity/kraan

somewhere.

**Comment by stefanprodan** [comment]
Also https://github.com/telekom/das-schiff

**Comment by stefanprodan** [comment]
Also https://github.com/microsoft/fabrikate & https://github.com/microsoft/bedrock

**Comment by dholbach** [comment]
https://github.com/weaveworks/weave-gitops

**Comment by stefanprodan** [comment]
https://github.com/pelotech/jsonnet-controller
