### ISSUE TITLE
patches documented in kustomization but not part of spec

### ISSUE THREAD

**Issue by nniehoff** [fluxcd/website#337]
[Patches](https://fluxcd.io/docs/components/kustomize/kustomization/#patches) is included in the documentation for a kustomization but is not part of the [spec](https://fluxcd.io/docs/components/kustomize/kustomization/#specification).  The specification does is correct, patches should be removed from the docs or noted that this feature doesn't exist yet.

**Comment by hiddeco** [comment]
Patches are available since the latest minor release: https://github.com/fluxcd/kustomize-controller/blob/main/CHANGELOG.md#0130
