### ISSUE TITLE
Network issue with LoadBalancer and Receiving Webhook guide

### ISSUE THREAD

**Issue by kingdonb** [fluxcd/website#359]
I have spent some time working with receiving webhooks on different clusters, and one thing I have noticed is that the LB method doesn't seem reliable when used together with NetworkPolicy. This may depend on your CNI or other details of the cluster hosting Flux. I'm opening a PR to improve the Webhook Receiver doc but it may need to cover multiple issues, some of which are not fully explored (some may be bugs) and I wanted to open a separate issue to track these details, rather than try to jam everything into one PR since that usually doesn't work out very well for me.

I am not certain how many people ran into the same errors I did when setting up a load balancer as described in this doc for receiving webhooks. We have received feedback from migration workshop "customers" that this part of the guide needs help.

The issue I had on DOK8s is that the load balancer was unable to communicate with the webhook receiver service on port 9292. I was using the default network policies and did not modify them at all. The CNI on DOK8s is Cilium. I confirmed that disabling the NetworkPolicy resources resolved the issue and made it so that the webhook was able to communicate via LB.

If there are changes to NetworkPolicy required in order to make the LoadBalancer version work when network-policy is enabled (as it is in the default bootstrap settings) then we should add some guidance here about this. If there is some CNI where the Receiving Webhook loadbalancer works out of the box with the default network policies, then I haven't found it yet (I don't want to assume because no reference platform is mentioned that it hasn't been formally tested), but if there is variability between CNI or something else to explain why it would work on some clusters but not others, I would like to make sure this issue is properly documented. I think my expectation is that NetworkPolicy should work the same everywhere.

Maybe the unstated expectation of our docs is that you're going to go in and configure the network policies to work with the load balancer; if so I did not know how to do that nor find any indication in the docs that it was expected, we should be clear.

We got this feedback during one of our FluxCD community migration workshops; the general feedback was that the Webhook docs don't quite explain enough. (The details I'm elaborating here are not specific feedback that we received from any user, these are my own ideas about how we could make the doc better.)

Probably before #358 (the first PR related to this issue) is merged, I'm going to try out both LB and Ingress on a kubeadm cluster (with calico and metallb) according to these instructions. I am not sure if the behavior of NetworkPolicy varies a bit more than you'd expect from provider to provider against my expectations, but our experience with Azure CNI and AKS indicates to me this may be a bit more wild-west than I was expecting.

I decided to try Ingress because the NetworkPolicy uses the words `Ingress` and `Egress` with a rule that explicitly says, "allow ingress to webhook-receiver" but I don't know enough about NetworkPolicy, and I think I may be reading too much into the word `Ingress` – I interpret this as probably meaning "allow the traffic to come in this way" not the more specific "allow Ingress resources to reach in through this way"

Nonetheless, the Ingress which was hosted from another namespace did not have any trouble connecting the outside world with the webhook-receiver at port 9292 in the flux-system namespace with all of the default NetworkPolicy rules in place. Not sure where to start learning to know more about NetworkPolicy rules and how they are configured with ingresses and load balancers. Maybe we could provide an outside reference. I may have seen a visual tool to help write better network policies...

**Comment by stefanprodan** [comment]
Duplicate of: https://github.com/fluxcd/flux2/issues/1448

**Comment by kingdonb** [comment]
Will follow up in https://github.com/fluxcd/flux2/issues/1448
