### ISSUE TITLE
Make buttons flat and crispy

### ISSUE THREAD

**Issue by dholbach** [fluxcd/website#369]
Some feedback was that we should use flat buttons instead again. <https://flagger.app> was quoted as an example.

**Comment by hiddeco** [comment]
![image](https://user-images.githubusercontent.com/10063039/123941575-93a22480-d99a-11eb-8041-3fc0923de240.png)

is a quick suggestion, but with the arrow icon added as Flagger has.

What I did to get there is change the background to `#fff`, drop all shadows around the text and button, and make the text color `#555`.

**Comment by dholbach** [comment]
cc @juozasg

**Comment by hiddeco** [comment]
This should probably be paired with a suggestion I made elsewhere to drop the shadow on the `h1` of the hero, which I can't find the issue / comment for at the moment.

**Comment by dholbach** [comment]
#136

**Comment by dholbach** [comment]
@hiddeco says
> There is still a 1px greenish border around the button that I have to remove / overwrite in my mock-up as well.

**Comment by juozasg** [comment]
Removed green 1px border https://github.com/juozasg/website/commit/950accff21c7daf304e6bdcbca5f8e72b58a1cc1

**Comment by dholbach** [comment]
I created a PR for you in #381.
