### ISSUE TITLE
Reenable foldable menu once g/docsy#616 is fixed

### ISSUE THREAD

**Issue by dholbach** [fluxcd/website#374]
#371 tries to address the issue but falls short.

If you check the sidebar menu on <https://fluxcd.io/docs> you can see that the list of Flux CLI articles is cut off.

Setting `params.ui.sidebar_menu_truncate` is part of the solution, but it doesn't fix everything.

Relevant code:

- https://github.com/fluxcd/website/blob/main/layouts/partials/sidebar-tree.html
- https://github.com/google/docsy/blob/master/assets/scss/_sidebar-tree.scss

**Comment by dholbach** [comment]
I found this is an issue in upstream docsy so I filed this issue with a minimal test-case: https://github.com/google/docsy/issues/616

Do we want to disable `sidebar_menu_foldable = true` for now?

**Comment by kingdonb** [comment]
I don't think we should disable the foldable sidebar, some of the sections are quite long and I'm not sure if it will be better.

**Comment by dholbach** [comment]
This was fixed in https://github.com/alisondy/website/commit/e3e20b5dfa26f61f909d08fc342850917d856ab7
