### ISSUE TITLE
Installation has a broken link for Installation for Azure DevOps

### ISSUE THREAD

**Issue by mahomedalid** [fluxcd/website#406]
https://fluxcd.io/docs/installation/ link to Azure DevOps should point to https://fluxcd.io/docs/use-cases/azure/#flux-installation-for-azure-devops it is pointing to https://fluxcd.io/docs/use-cases/azure.md#flux-installation-for-azure-devops instead which causes a broken link.

**Comment by kingdonb** [comment]
Thanks for the report! I found the `docker-support` stuff that is meant to make the website repo easy to maintain needs a bit of updating. I'll close both of these issues in a PR together.
