### ISSUE TITLE
"Flux in short" emojis look tiny on mobile

### ISSUE THREAD

**Issue by juozasg** [fluxcd/website#410]
On narrower screens, this layout leaves a lot of blank space in the second column. It might look better removing the icons completely on mobile - or having them in the second column, to use some of the free vertical space. 

This ![image](https://user-images.githubusercontent.com/4100/125464213-04a6d59d-022b-4566-a498-2fc5d274210b.png)

vs this (with a better grid layout)

![image](https://user-images.githubusercontent.com/4100/125466204-247b30d3-dcb3-4a5b-af68-78fbc7b41779.png)

**Comment by dholbach** [comment]
Yeah, good thinking! If you can send a PR for this, let's get it in!

**Comment by juozasg** [comment]
@dholbach https://github.com/fluxcd/website/pull/455
