### ISSUE TITLE
Declare less Hugo versions

### ISSUE THREAD

**Issue by dholbach** [fluxcd/website#434]
We currently specify in many different places which version of hugo to use:

```cli
website on  main [$] via  v12.22.4 via 🐍 v3.8.10
❯ git grep 0.86.0
Makefile:HUGO_VERSION               ?= 0.86.0
docker-support/Dockerfile:FROM fluxcd/website:hugo-0.86.0-extended
netlify.toml:  HUGO_VERSION = "0.86.0"
package-lock.json:      "version": "0.86.0",
package-lock.json:      "resolved": "https://registry.npmjs.org/hugo-extended/-/hugo-extended-0.86.0.tgz",
package.json:    "hugo-extended": "^0.86.0",
website on  main [$] via  v12.22.4 via 🐍 v3.8.10
```

Right now, only `package*.json` are updated through dependabot. AFAIK, only `netlify.toml` is relevant for building the website? Can we slim this down somewhat?

@hiddeco @kingdonb Do you have any input on this?

**Comment by kingdonb** [comment]
The convention in Ruby that I've seen to avoid duplicating the version is to put a file `.ruby_version` which is honored by some version managers, and use string interpolation to get that pulled into the Gemfile. That's not possible with package.json (and wouldn't work well for Dockerfile either.)

I think the best we can do is to build some CI job around the docker-support image, it should keep the published website support image updated on some cycle, and assert that versions in all of these places are correctly aligned. This can be something I could take a look at.

**Comment by dholbach** [comment]
Is https://github.com/fluxcd/website/blob/main/Makefile#L126-L127 used at all anywhere?

**Comment by yebyen** [comment]
Yes, this builds the base image since Hugo upstream doesn't provide one with the flags we need (or one per version at all)
