### ISSUE TITLE
docker-support/Dockerfile: use requirements.txt in pip call

### ISSUE THREAD

**Issue by dholbach** [fluxcd/website#451]
AFAICS https://github.com/fluxcd/website/blob/main/docker-support/Dockerfile#L18 is missing `pygithub` which is specified in https://github.com/fluxcd/website/blob/main/requirements.txt - so maybe let's use `pip install -r requirements.txt` instead?

@kingdonb Does this make sense?

**Comment by kingdonb** [comment]
Yes that makes sense, I'll give it a test with the change you suggested today. With the upgrade to 20.04 as a base, the Docker image is going to need to be refreshed to stay in sync anyway. 👍
