### ISSUE TITLE
Refresh of resources section

### ISSUE THREAD

**Issue by staceypotter** [fluxcd/website#457]
It's been a while since we updated the Resources section (see #90) and it's time for a refresh to this section. I would like to propose the following, but open to other suggestions.

1.  The Power of GitOps with Flux Playlist (https://youtube.com/playlist?list=PL9lTuCFNLaD3fI_g-NXWVxopnJ0adn65d)
Description: This playlist is designed to show the powerful GitOps capabilities of Flux (and the GitOps Toolkit). Videos include project overviews, reviews, technical demos, and walk-throughs of our guides. 

2.  Flux Deep Dive with Stefan Prodan (https://youtu.be/Fzzg4KQavEU)
Description: Stefan walks through what Flux is, who it’s for and it’s components. Then gives a demo on how to use Flux for delivering infrastructure and applications changes onto Kubernetes.

3.  From Wild West to Flux Multi-tenancy with Mae Large & Russ Parmer (https://youtu.be/NLU6b82FhFs)
Description:  Mae and Russ share how the State Farm GitOps team helped to simplify application deployment while meeting compliance requirements, enable the admin team to handle scale, embrace the declarative nature of kubernetes, increase transparency, and mature the shared responsibility model between administrators and consumers of our kubernetes platform.

4.  Flux's Catalog - Keeping Track of Things! with Leigh Capili (https://youtu.be/gfyo6VqgD_k)
Description:  Leigh Capili gives us a black belt, under-the-covers look at how Flux's kustomize-controller tracks the child objects for a Kustomization in the Kubernetes API. He demonstrates how labels, checksums, and a GVK+Namespace list called the catalog can be used together to build detailed Object trees of everything Flux is managing in a cluster. This design is transparent, ergonomic, and performant! Learn how to use Flux's object tracking in your own extensions and UI's atop Flux and the GitOps Toolkit as 

5.  Handling Dependencies with Flux with Jason Morgan (https://youtu.be/laMwuG8r7Tw)
Description:  Kubernetes provides a simple way to apply configuration against a cluster but sometimes the order of operations matters. Using a tool like a service mesh requires that the control plane and proxy injector, a mutating webhook, be ready before you install your applications. Jason walks through how to use Flux’s dependency manager to ensure that your apps get added to your mesh every time.

6.  Flux v2 Deep Dive series with Geert Baeke: https://www.youtube.com/playlist?list=PLG9qZAczREKmCq6on_LG8D0uiHMx1h3yn
Description: In this 5 video series, Geert Baeke takes a deep dive of Flux v2 and the use of GitOps principles with an Intro to Flux v2, Intro to Kustomize, Deploying Manifests, Monitoring & Alerting, and Helm Basics.

**Comment by staceypotter** [comment]
cc @dholbach :)

**Comment by dholbach** [comment]
Please take a look at https://github.com/fluxcd/website/pull/459 and its preview.

I need to find a good way of showing nicer previews for the playlist links - it looks a bit bland otherwise.

The selection of videos is great - thanks @staceypotter
