### ISSUE TITLE
lychee link checker fails

### ISSUE THREAD

**Issue by dholbach** [fluxcd/website#470]
https://github.com/fluxcd/website/runs/3380347792?check_suite_focus=true failed like so

```cli
Run lycheeverse/lychee-action@v1.0.8
/usr/bin/docker run --name c9e0362409e998569248b09d2ff999ad0dd1cf_4eaa2b --label c9e036 --workdir /github/workspace --rm -e pythonLocation -e LD_LIBRARY_PATH -e GITHUB_TOKEN -e INPUT_ARGS -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/website/website":"/github/workspace" c9e036:2409e998569248b09d2ff999ad0dd1cf --verbose --no-progress --exclude-all-private content/en/docs/get-started.md content/en/docs/installation.md
standard_init_linux.go:228: exec user process caused: no such file or directory
```

**Comment by NissesSenap** [comment]
I can take a look at it, you can assign it to me.

**Comment by NissesSenap** [comment]
I have been looking around, I ran the commands locally and it works as intended. I created a PR just to test it out: https://github.com/NissesSenap/website/pull/3 and it works fine.
I don't have enough access, what happens if you re-trigger the job manually in https://github.com/fluxcd/website/pull/469?
I looked at a few other PR:s and I see that the job works fine.

**Comment by dholbach** [comment]
I re-ran the check once, and it failed the same way. 🤷‍♂️

**Comment by NissesSenap** [comment]
I have no good idea on how to debug this, for now I would say lets ignore it and see if it happens again...
With the current information the only thing I can come up with is that for some reason that file wasn't checkout as it should have been, but at the same time github action didn't complain.

If I we had more powers over the infrastructure I would say clean out the local disk to get rid of any strange cashes of the node and run again.

**Comment by dholbach** [comment]
Thanks for taking a close look at this @NissesSenap - looks like the check worked just fine in #471. Closing for now - we'll re-open if it happens again.

cc @stefanprodan - apparently it was an intermittent issue.
