### ISSUE TITLE
Unable to bootstrap flux in multiple repositories of the same cluster

### ISSUE THREAD

**Issue by Meghavenkatesh** [fluxcd/website#499]
I am trying to bootstrap flux of repo1 and repo2 in cluster1, after running the command 

```
flux bootstrap gitlab \
--hostname=https://gitlab.com/repo1.git \
--owner=root \
--repository=repo1 \
--branch=master \
--token-auth \
--personal
```

flux is bootstrapped and repo1 will create a flux-system folder and source and kustomization is created.

`kubectl get gitrepositories.source.toolkit.fluxcd.io -n flux-system`

output: 

|NAME                |  URL                                    |                  READY                               |     
| ------------------|---------------|----------- |
|repo1              |   https://gitlab.com/repo1.git       |         true                                   |         
|flux-system         |https://gitlab.com/repo1.git           |     true                                   |

but after sometime if i bootstrap the repo2 in the same cluster1, 
```
flux bootstrap gitlab \
--hostname=https://gitlab.com/repo2.git \
--owner=root \
--repository=repo2 \
--branch=master \
-| token-auth \
--personal
```
flux-system points to repo2 and source and kustomizations of repo1 and repo2 both will be present
 

`kubectl get gitrepositories.source.toolkit.fluxcd.io -n flux-system`

output: 
|NAME                                   |       URL                                      |                READY   |   
| ------------------|---------------|----------- |                               
|repo1                                |    https://gitlab.com/repo1.git       |         true               |                              
|flux-system                         |   https://gitlab.com/repo2.git       |         true|
|repo2                                  |   https://gitlab.com/repo2.git     |           true |  

but after few seconds, the newly created repo2 source and kustomization disappears and the cluster1 will have the previous state that is of repo1 

`kubectl get gitrepositories.source.toolkit.fluxcd.io -n flux-system`

output: 
|NAME                |  URL                                     |                 READY      |
| ------------------|---------------|----------- |                                     
|repo1            |     https://gitlab.com/repo1.git |               true             |                                
|flux-system    |    https://gitlab.com/repo1.git  |              true|

structure following is:

![image](https://user-images.githubusercontent.com/14858986/132230679-6e3ac900-61c9-46df-8308-d293f69ecd3e.png)

Is there any reason on why the flux is behaving like this and any way to achieve the following scenario ?

**Comment by stefanprodan** [comment]
You should run bootstrap only once for the main repo, then add all the other repos as GitRepositories manifests in the main one.  Please see the docs here: https://fluxcd.io/docs/guides/repository-structure/
