### ISSUE TITLE
Write import script to pull in data from other repositories

### ISSUE THREAD

**Issue by hiddeco** [fluxcd/website#50]
As this will become our hub for all website and documentation related things, the developer orientated `README.md` should be rewritten to welcome contributors of all kinds.

The `kubernetes/website` repository has a great example: https://github.com/kubernetes/website

**Comment by dholbach** [comment]
Hum, is this https://github.com/fluxcd/community/pull/48 (addressing fluxcd/community#6)?

If yes, we could make this issue about importing docs from elsewhere, e.g. making the /f/community README be fluxcd.io/community?

**Comment by dholbach** [comment]
https://github.com/kubernetes-sigs/contributor-site/blob/master/hack/gen-content.sh is what brings this kind of functionality to <https://kubernetes.dev>

cc @alisondy

**Comment by dholbach** [comment]
cc @somtochiama

**Comment by dholbach** [comment]
Fixed by https://github.com/fluxcd/website/pull/74
