### ISSUE TITLE
Update docs PR template

### ISSUE THREAD

**Issue by alisondy** [fluxcd/website#503]
remind people to check over the style guide
assign reviewers

**Comment by kingdonb** [comment]
Do we want to investigate and find a way to assign reviewers to new PRs automatically when they come in?

We are here looking at the style guide now, at the Bug Scrub 🎉

**Comment by alisondy** [comment]
@kingdonb I would love to autoassign reviewers but think we should make a separate issue for this

regarding codeowners we would have to decide how and where to delegate which is another issue in itself - if we're thinking of doing stuff like separate codeowners for separate areas

**Comment by alisondy** [comment]
closing issue as dupe of #213
