### ISSUE TITLE
Generate fluxcd/website docker images through GH Action

### ISSUE THREAD

**Issue by dholbach** [fluxcd/website#522]
As a follow-up to #502 - let's generate fluxcd/website docker images through a GH workflow. Discussed in https://cloud-native.slack.com/archives/C01A402P0R2/p1631017482043800

**Comment by dholbach** [comment]
Stefan says:
> best is to create a manual job, the secrets are:
> DOCKER_FLUXCD_USER and DOCKER_FLUXCD_PASSWORD

**Comment by kingdonb** [comment]
This is closed by #566

**Comment by dholbach** [comment]
```
#17 ERROR: authorization status: 401: authorization failed
```

@stefanprodan Can you help us here find the right credentials?

**Comment by yebyen** [comment]
We could follow this up with further enhancement to use https://github.com/marketplace/actions/file-changes-action to try to ensure that the workflow runs when one of the files changes that would indicate a new support image is needed

**Comment by dholbach** [comment]
> ```
> #17 ERROR: authorization status: 401: authorization failed
> ```
> 
> @stefanprodan Can you help us here find the right credentials?

Or anyone else in @fluxcd/oversight-committee ?

For context #566 added workflows which generate images that can be used for working on the website locally. Not sure why
> DOCKER_FLUXCD_USER and DOCKER_FLUXCD_PASSWORD
don't work. :man_shrugging:

**Comment by stefanprodan** [comment]
@dholbach try again now, I have added the bot to `fluxcd/website` with write permissions.

**Comment by dholbach** [comment]
Excellent - this worked - thanks so much!
