### ISSUE TITLE
'get changed files' in link checker workflow does not always work

### ISSUE THREAD

**Issue by dholbach** [fluxcd/website#533]
https://github.com/fluxcd/website/pull/532/checks?check_run_id=3662342724 fails for example.

https://github.com/fluxcd/website/blob/main/.github/workflows/lychee-pr.yaml#L17-L26 is the code in question.

**Comment by NissesSenap** [comment]
I think I know why:
`echo "::set-output name=ts::$(git diff --name-only --diff-filter=ACMRT origin/main... |grep .md |xargs)"`
searches for markdown files.

In https://github.com/fluxcd/website/pull/532/files you don't update any .md files but just a HTML file. We should be able to find some good filter solution for it. One solution could possibly to only trgiger the CI on updates to *,md

**Comment by dholbach** [comment]
Thanks a lot @NissesSenap for the analysis! Well done!
