### ISSUE TITLE
Update front page description

### ISSUE THREAD

**Issue by mewzherder** [fluxcd/website#536]
Current text: 

Flux is a set of continuous and progressive delivery solutions for Kubernetes, and they are open and extensible.
The latest version of Flux brings many new features and **made** Flux more flexible and versatile.
Flux is a CNCF Incubating project.

Suggest changing to:
Flux is a set of continuous and progressive delivery solutions for Kubernetes, and they are open and extensible.
The latest version of Flux brings many new features and **makes** Flux more flexible and versatile.
Flux is a CNCF Incubating project.

**Comment by alisondy** [comment]
https://github.com/fluxcd/website/pull/541

The line

```
  Flux is a set of continuous and progressive delivery solutions for Kubernetes that are open and extensible.
```

could be simplified down to 

```
  Flux is a continuous and progressive delivery solution for Kubernetes that is open and extensible.
```

**Comment by alisondy** [comment]
Closing this for now as merged PR
