### ISSUE TITLE
Blurry line between Flux and GitOps Toolkit

### ISSUE THREAD

**Issue by dholbach** [fluxcd/website#587]
# Blurry line between “GitOps toolkit” and “Flux”

> [..] when going through the documentation
> (https://fluxcd.io/docs) sequentially, then the first mention of “GitOps toolkit” is in the second
> page within the “Guides” section, named “Helm Releases”:
> https://fluxcd.io/docs/guides/helmreleases/
> On this page it says a prerequisite to the guide is to have a Kubernetes cluster with the
> GitOps controllers installed and then referencing the getting started and installation guides,
> as shown by the following Figure.

![grafik](https://user-images.githubusercontent.com/1346979/137730734-880e173c-0fcb-46df-8b09-a0c096141faa.png)

> However, “GitOps toolkit” is not mentioned on these pages.
> In addition to the above observations, the current destination of the link to the gitops toolkit
> on the fluxcd.io page, namely https://fluxcd.io/#gitops-toolkit, does not lead anywhere. This is
> the link on the rightmost box on the website as shown by the following Figure:

![grafik](https://user-images.githubusercontent.com/1346979/137730794-6cb055c1-c636-4b9b-9433-02c6b4b8ab6a.png)

##  Recommendation

> Flux uses names and concepts conservatively to easily convey the structure of the
> infrastructure. However, the documentation must have an equal structure including proper
> introduction of concepts. We recommend using clear naming of the components in the
> system and ensuring proper introduction without broken links or links to pages that do not
> clarify concepts that were promised. It would be a great assistance to have a page that
> unifies the nomenclature of Flux and links to details about the definition or where the concept
> is introduced.

**Comment by priyanka-ravi** [comment]
I can attempt to tackle this one!

**Comment by scottrigby** [comment]
Re this part:
> It would be a great assistance to have a page that unifies the nomenclature of Flux and links to details about the definition or where the concept is introduced.

I pointed @priyanka-ravi to this PR, which I had still needed to update. Now updated  to resolve @squaremo's later suggestions. 

@priyanka-ravi  is reviewing now with this issue above in mind. This is essentially a unified page clearly disambiguating nomenclature about the various things we refer to when saying “Flux”, how it relationship to GitOps Toolkit, etc. Once reviewed again, we can update website automation to pull it somewhere into the docs.

**Comment by dholbach** [comment]
After fluxcd/community#122 is merged, what will need to be done? Do we generally just want to reduce the GOTK mentions and make clear that on e.g. `/docs/`, `/docs/concepts` and `/docs/components` and `docs/gitops-toollkit` it's well-explained?

**Comment by dholbach** [comment]
@priyanka-ravi Can you take a look at the PR?

Does the general (beginner) flow through docs on https://deploy-preview-728--fluxcd.netlify.app/ and https://deploy-preview-728--fluxcd.netlify.app/docs make more sense? (I tried to mention GOTK less and centralise the explanation of GOTK a bit more.)
