### ISSUE TITLE
Documenting the use of sensitive data by Flux in the cluster 

### ISSUE THREAD

**Issue by dholbach** [fluxcd/website#595]
> Currently Flux provides no central documentation on the security of Flux. This is an issue as a user might expose more data than anticipated and currently has to read the implementation to identify these concepts. 

> Document the security context of Flux in a central location. Topics that are useful to document on such a page include: 
> 1. The sensitive data that Flux uses. 
> 2. The attack surface of Flux. 
> 3. What are the consequences of a compromise of Flux/component of Flux 4. Who should be allowed to administer Flux within an Organisation 
> 5. Security hardening of Flux, i.e. Flux can be used in many ways and what are the best practices from a security perspective and what are some of the pitfalls that can happen 

> Open source projects that have examples of this: 
> ● Docker: https://docs.docker.com/engine/security/ 
> ● Envoy: https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/security/security
>    ○ In particular the threat model

**Comment by scottrigby** [comment]
WIP for outlining how Flux correctly handles sensitive data during bootstrap, such as keys, and what the best practices are.

## Bootstrapping

- flux addresses 2 security:
- source (git repo, helm, buckets etc)
    - we have to talk about the security here, and what bootstrap does. 
    - asks for token for Github and GitLab etc
    - by default, we don't use token in cluster. it never leaves your machine
    - we use that to generate a deploy key, and we use that within the cluster
    - we're getting this question on slack a lot
    - but what if you do want flux to use a PAT? to give flux access to all repos in your org?
        - solution is you great a user for flux, and bootstrap using flux bot user token
        - then you can do this using the special flag in bootstrap `--token` and only if you do that, will flux use this in cluster
        - we must explain this in best practices
            - don't use your user PAT with --token
            - instead, use a Github machine user

**Comment by scottrigby** [comment]
Issue closed by #641 and #711.

Will open a follow-up issue to address possible enhancements as mentioned in https://github.com/fluxcd/website/issues/595#issuecomment-976151045.

**Comment by dholbach** [comment]
What from https://github.com/fluxcd/website/issues/595#issuecomment-976151045 is still missing?

**Comment by scottrigby** [comment]
> What from [#595 (comment)](https://github.com/fluxcd/website/issues/595#issuecomment-976151045) is still missing?

Not necessarily missing. Elaborated here: https://github.com/fluxcd/website/issues/721#issuecomment-1021399424
