### ISSUE TITLE
Release cycle information and expectation

### ISSUE THREAD

**Issue by dholbach** [fluxcd/website#596]
We have https://github.com/fluxcd/flux2/blob/main/docs/internal/release.md but we currently are lacking user-targetted

> security-relevant information such as how long versions are supported and how often to expect releases. 
> Examples of open source projects that describe their release cycle: 
> ● Kubernetes: https://kubernetes.io/releases/version-skew-policy/ 
> ● Redis: https://redis.io/topics/releases 
> ● Linux kernel: https://www.kernel.org/category/releases.html

Maybe make this a section in a top-level `/docs/security` page?

**Comment by pjbgf** [comment]
We already have some of this information in the [Migration Timetable page](https://fluxcd.io/docs/migration/timetable/) (e.g. support / version skew policy). 

But thing such as release cycle, version support and skew policy deserve a standalone page. 
This make even more sense for folks new to flux, outside the "migration path".
