### ISSUE TITLE
Image Repositories

### ISSUE THREAD

**Issue by TreverW** [fluxcd/website#601]
> The controller must be run with the flag --aws-autologin-for-ecr set for this to work. 

Which controller?  When I tried adding this to the Image Reflector Controller, it failed to run. 
>unknown flag: --aws-autologin-for-ecr

**Comment by dholbach** [comment]
Is this still an issue now?

**Comment by kingdonb** [comment]
Yes, it should be fixed by fluxcd/image-reflector-controller#193.
