### ISSUE TITLE
Error Running `make docker-preview`

### ISSUE THREAD

**Issue by Nalum** [fluxcd/website#645]
When running `make docker-preview` I am getting the following error:

```
Error: Error building site: "/site/content/en/blog/2021-10-29-november-update/index.md:246:1": failed to render shortcode "tweet": failed to process shortcode: template: _internal/shortcodes/tweet.html:6:82: executing "_internal/shortcodes/tweet.html" at <index .Params 0>: error calling index: value has type int; should be string
```

I think this might have to do with the version of hugo that is used in the docker image `fluxcd/website:hugo-support`:

```hugo v0.88.1+extended linux/amd64 BuildDate=2021-10-04T10:06:47Z```

The version in the `netlify.toml` config is `0.89.4` and testing this version installed locally works as expected.

**Comment by yebyen** [comment]
There is a job which has to be run manually by a maintainer after the Hugo version is upgraded, to update the build machinery in the image. Let me see if I have access to run it. It should take about 15 minutes to resolve this.

**Comment by kingdonb** [comment]
Running the second of the two jobs now...

FYI it is also possible to build your own support images but thank you for reporting this, the published images should be kept up to date 😄 

Was pushed: a new
* `docker.io/fluxcd/website:hugo-0.89.4-extended@sha256:a3417d2f2b435621928c7bd16e913227430fca8d02857cfe1b3ff1eb55765d7b`
* `docker.io/fluxcd/website:hugo-support@sha256:8ba87fd11757602f2b45b9626d6b69e3cc742e8ff3fb7c6ab5d7a8b8981d8710`

Please let us know if this helps 👍

**Comment by Nalum** [comment]
Thanks @kingdonb it is working for me now :+1:
