### ISSUE TITLE
Broken link on website - community-roles.md

### ISSUE THREAD

**Issue by kingdonb** [fluxcd/website#680]
There is this doc for governance:

https://github.com/fluxcd/community/edit/main/GOVERNANCE.md

which includes the markdown text:

```
## Roles in the Flux Community

See [community-roles.md]
```

If you're reading this on GitHub, that link works fine, but when the governance doc gets imported into the website here, the link is broken:

https://fluxcd.io/governance/#roles-in-the-flux-community

The link gets directed here, which is our lovely 404 page, shows this `community-roles.md` doc does not apparently get imported into anywhere in the website's search path. I'm not sure how to fix this best, but we should definitely fix it.

(the link that 404s: https://fluxcd.io/governance/community-roles.md)

**Comment by dholbach** [comment]
This should be fixed in https://github.com/fluxcd/website/blob/main/hack/gen-content.py#L85 somewhere...
