### ISSUE TITLE
Legacy docs are difficult to find

### ISSUE THREAD

**Issue by kingdonb** [fluxcd/website#689]
We have intentionally de-emphasized Flux v1 from all literature for marketing reasons, and while Flux v1 still receives a mention on the front page, that appears to be the only remotely accessible place that actually links to https://fluxcd.io/legacy/flux/ which is the new home of https://docs.fluxcd.io

Is this too inaccessible now? I think we had "Flux v1/Legacy" in the topbar menu under "Docs" at one point, and removed it (on purpose, ostensibly because we have made a conscious decision that we are not building versioned docs until at least after v2.0) – I think it should be in the menu, or anywhere more accessible than the only place it is now.

Finding the first mention of Flux v1 at 80% down the scrollbar, after 11 pages of content, is a bit more inaccessible than ideal. (In the bottom of a locked filing cabinet, stuck in a disused lavatory with a sign on the door...)

**Comment by dholbach** [comment]
This can be closed because the Legacy docs reached their End Of Life.
