### ISSUE TITLE
Variable substitution escaping operator

### ISSUE THREAD

**Issue by gvillafanetapia** [fluxcd/website#705]
It would be great to add [in the doc](https://fluxcd.io/docs/components/kustomize/kustomization/#variable-substitution) that to escape this operator you need to use double dollar sign; `$${my_substitute_var}`

Had to find out by trial and error 😛

**Comment by stefanprodan** [comment]
The doc source is here: https://github.com/fluxcd/kustomize-controller/blob/main/docs/spec/v1beta2/kustomization.md#variable-substitution

**Comment by gvillafanetapia** [comment]
Oh, right!

But we were trying to use [this feature](https://github.com/airflow-helm/charts/tree/main/charts/airflow#option-2---use-templates-from-secretsconfigmaps-1) of the Airflow Community Helm chart and needed to print `${VAR}` **with** the curly braces.

Thanks

**Comment by gvillafanetapia** [comment]
Opened a PR https://github.com/fluxcd/kustomize-controller/pull/537 to address this 🙂
