### ISSUE TITLE
Get Started with Flux

### ISSUE THREAD

**Issue by borjaOrtizLlamas** [fluxcd/website#710]
hi, do you have any docker container with flux v2? 

best regards

**Comment by kingdonb** [comment]
Yes, there is a GHCR package (docker container) which does include the Flux v2 CLI:

https://github.com/fluxcd/flux2/pkgs/container/flux-cli

The individual controllers each are published in a separate container image as well, the Flux CLI handles installing them for you. You can build your own container images from this image if you want them to have the latest Flux CLI 👍

**Comment by dholbach** [comment]
@kingdonb Not sure ... Is this a common use-case we might want to document somewhere?
