### ISSUE TITLE
Reconsider migration guides placement

### ISSUE THREAD

**Issue by dholbach** [fluxcd/website#718]
From the CNCF Tech Docs assessment of our docs (cncf/techdocs#89):

>    - The [Migration](https://fluxcd.io/docs/migration/) section isn't more important than [Toolkit components](https://fluxcd.io/docs/components/), [Toolkit dev guides](https://fluxcd.io/docs/gitops-toolkit/), or the [Flux CLI reference](https://fluxcd.io/docs/cmd/). Placing it above these in the information architecture doesn't make sense. 
> 
> ### Recommendations
> 
> - Move the [Migration Guide](https://fluxcd.io/docs/guides/) to either a subsection of [Get Started](https://fluxcd.io/docs/get-started/) or a subsection of [Installation](https://fluxcd.io/docs/installation/)
>    - Consider renaming "Migration guide" to "Migrate from Flux v1" for clarity

**Comment by Neilblaze** [comment]
@dholbach is this open to contributions? If yes, I'd like to raise a PR regarding it.

**Comment by dholbach** [comment]
This issue is linked with #717

**Comment by Hammadh7** [comment]
I am interested in this issue

**Comment by stefanprodan** [comment]
Having migration under installation would confuse most Flux users, as this about migrating from a deprecated version (v1) and not about migrating between v2 releases. We'll probably have a migration section, for v2 APIs GA, alpha to stable controllers and so on.
