### ISSUE TITLE
Website: Show an example of Notification providers of Microsoft Teams

### ISSUE THREAD

**Issue by kingdonb** [fluxcd/website#738]
https://fluxcd.io/docs/components/notification/ does not seem to have any Microsoft Teams example under any section.

Some users have expressed that they had difficulty with this configuration, I'm not sure what is unusual about the configuration that we should address in a doc. (Someone with a Teams account and access to connect webhooks to it will have to try it, and write down their findings.)

### Discussed in https://github.com/fluxcd/flux2/discussions/957

<div type='discussions-op-text'>

<sup>Originally posted by **hatzhang** February 20, 2021</sup>
There is only an example of Slack in the manual,  can the team give an example of Microsoft Teams as providers ?</div>

**Comment by SomtochiAma** [comment]
Hey @kingdonb ,
I think we can add this in [https://fluxcd.io/docs/components/notification/provider/#notifications](https://fluxcd.io/docs/components/notification/provider/#notifications) where we have examples for other notification providers.
I will make a pull request in the notification-controller repo that page is from.
