### ISSUE TITLE
Renovate integration: call-out somehow in docs

### ISSUE THREAD

**Issue by kingdonb** [fluxcd/website#740]
Renovate is a paid SaaS product with a (slightly limited) free-use tier.

https://github.com/fluxcd/flux2/discussions/2293#discussioncomment-2118521 mentioned that Renovate has a specific, current [Flux manager](https://docs.renovatebot.com/modules/manager/flux/) which integrates such useful features as "automatically opening a PR for HelmRelease chart version upgrades when they are available" and even upgrading Flux itself.

Since this first feature is not available anywhere in Flux, I thought we should call this out. I'm not sure of the disposition of Flux toward mentioning freemium products by companies who do not contribute directly to Flux, but I am sure it could be at the very least added to the Integrations page: https://fluxcd.io/integrations/

Given this is a commonly requested feature though, I was hoping to mention it specifically in the docs, somewhere a bit more embedded/accessible and discoverable with reference to the specific capabilities it offers. WDYT?

**Comment by kingdonb** [comment]
Ongoing discussion already: https://github.com/fluxcd/flux2/discussions/2394

**Comment by kingdonb** [comment]
Before we advertise this, we should make sure this issue gets addressed: 

* https://github.com/renovatebot/renovate/issues/13952

Users who add Renovate to their repos are already reporting that it removes `components-extra` and can't apparently be configured to retain the extra controllers for now, ideally it will read the manifest and intuit which controllers should be used.

**Comment by dholbach** [comment]
Thanks for highlighting this - I'll back it out of `/integrations` for now.

**Comment by kingdonb** [comment]
I may also have mischaracterized Renovate, according to their docs:

> Renovate documentation[¶](https://docs.renovatebot.com/#renovate-documentation)
> Renovate (often referred to as "Renovate Bot") is an Open Source tool to automate:
> 
> * Detecting dependencies in a repository (Open Source and private/closed source)
> * Checking if there are newer versions which can be updated to
> * Creating commits and Merge/Pull Requests to apply such changes, and show the Release Notes (if available)

If it is really open source, then there may be no qualms about including it in our docs in a first-class way. There is definitely a paid offering but I don't think we have any prohibition on mentioning paid offerings in our docs, where the SaaS offering is also available as fully open source.

**Comment by danports** [comment]
Wow, thanks for the rapid & vigorous discussion here! I wasn't expecting such a flurry of activity. 🚀 😅

I agree with @onedr0p's assessment that Renovate is fully open source. In fact, when I reviewed the [Whitesource product page for Renovate](https://www.whitesourcesoftware.com/free-developer-tools/renovate/) again just now, I couldn't find any mention of purchasing, nor any mention of a closed source/paid version of Renovate (e.g. an enterprise version with additional features). Whitesource does have a paid ["Full Solution"](https://www.whitesourcesoftware.com/free-developer-tools/full-solution/) offering that apparently integrates several of their open source products with some additional functionality into a web UI, but I don't think that impacts our considerations here.

I think it would be helpful if the Flux docs more clearly outlined day 1/day 2 operations, the GitOps workflow, and how Renovate fits into that. Right now, the [Guides](https://fluxcd.io/docs/guides/) and the [Use Cases](https://fluxcd.io/docs/use-cases/) sections are like cookbooks with a mish-mash of various recipes, which is a little bit confusing. I'd suggest reorganizing the contents of those sections into two new sections: Installation/Configuration (i.e. day 1) and Operations (i.e. day 2). Then I'd add an Operations subsection to discuss manual and automated upgrades via `flux bootstrap`, the GitHub Action, Renovate, etc. I'd probably put the Prometheus monitoring guide and migrations bits in the Operations section too.

**Comment by dholbach** [comment]
Thanks @danports for your feedback.

> I think it would be helpful if the Flux docs more clearly outlined day 1/day 2 operations, the GitOps workflow, and how Renovate fits into that. Right now, the [Guides](https://fluxcd.io/docs/guides/) and the [Use Cases](https://fluxcd.io/docs/use-cases/) sections are like cookbooks with a mish-mash of various recipes, which is a little bit confusing. I'd suggest reorganizing the contents of those sections into two new sections: Installation/Configuration (i.e. day 1) and Operations (i.e. day 2). Then I'd add an Operations subsection to discuss manual and automated upgrades via `flux bootstrap`, the GitHub Action, Renovate, etc. I'd probably put the Prometheus monitoring guide and migrations bits in the Operations section too.

I'll copy this to https://github.com/fluxcd/website/issues/717

**Comment by danports** [comment]
I've partially addressed https://github.com/renovatebot/renovate/issues/13952 in https://github.com/renovatebot/renovate/pull/14332 by adding support for `--components` when generating Flux system manifests. Would you folks be open to a Flux PR to add the options used to generate the system manifest to the manifest header as discussed [here](https://github.com/renovatebot/renovate/issues/13952#issuecomment-1031904064)? That way we could easily grab the install options in Renovate without resorting to potentially fragile regexes to extract the options from the contents of the manifest or duplicating the options in the Renovate configuration.

**Comment by kingdonb** [comment]
I think that's a great idea after our conversation before, I think everyone will agree that Renovate should not try to parse the manifests and infer Flux's bootstrap configuration based on what is found or missing there.

Flux team, how do we feel about adding more information to the "DO NOT EDIT" section at the top of `gotk-components.yaml`? I think our design is that, any `bootstrap` (or `install`) option which leaves a footprint on the manifests, should leave enough metadata behind for upgraders to reproduce them on future versions. This idea can have some thought and iteration, but in principle what do we think?

I think only `install` should suffice as Renovate should not need to run `bootstrap` again, only `install --export` (I think the list in https://github.com/renovatebot/renovate/issues/13952#issuecomment-1046449269 looks correct at a glance.)

**Comment by dholbach** [comment]
Can this be resolved?

**Comment by kingdonb** [comment]
I think so. The missing parts are not related to the core issue, which is that "we can't really advertise renovate if it's going to remove image controllers when people use it to upgrade Flux" – it's still true that renovate will wipe out things like `--network-policy=false` but those options can all be worked around. And now, we are calling out renovate in the docs:

https://fluxcd.io/ecosystem/#ancillary-tools

We already merged the note adding this back to ecosystem tools, after @danports added those fixes to Renovatebot. It's not searchable in our docs for some reason, (but still that is not the same issue.)
