### ISSUE TITLE
Automate import of docs

### ISSUE THREAD

**Issue by dholbach** [fluxcd/website#75]
Now that #74 is sorted, we might want to look into automating this. Would it be e.g. possible to have a cron job which runs the `hack/gen-content.sh` script and create a PR if there's a diff?

**Comment by hiddeco** [comment]
Given we do not store a copy in this repository, I do not think it should create a PR.

Instead, we should probably run a GitHub action `x` times a day that [triggers a manual Netlify build](00340435050145502616).

**Comment by dholbach** [comment]
Thanks for digging this out. This might be the best course of action.
