### ISSUE TITLE
Subsume flux2 docs under fluxcd.io/docs

### ISSUE THREAD

**Issue by dholbach** [fluxcd/website#76]
As discussed in https://github.com/fluxcd/flux2/discussions/367 we want to move the docs like so:

. | Now | Future
-- | -- | --
Docs Website | toolkit.fluxcd.io | fluxcd.io/docs
User Guides | toolkit.fluxcd.io/guides | fluxcd.io/docs/flux
Dev Guides | toolkit.fluxcd.io/dev-guides | fluxcd.io/docs/gitops-toolkit

The proposal did not quite discuss what would happen with
- docs.fluxcd.io (v1 docs) and
- https://flagger.app (now part of /fluxcd)

Once we have a URL structure figured out for everything we can start implementing. Maybe we do this in 3 stages - first as discussed in the discussion linked above Flux v2 docs only.

**Comment by stefanprodan** [comment]
I propose we keep docs.fluxcd.io and docs.flagger.app as they are. After Flagger v2 we should consider merging the docs into fluxcd.io website.

**Comment by dholbach** [comment]
Ok. Let's make this issue just about Flux v2 docs - it's already enough work on its own.
