### ISSUE TITLE
Configure image automation authentication - containercannotrun issue

### ISSUE THREAD

**Issue by js-johnpope** [fluxcd/website#797]
I am new to flux and working my way through an install of it.  I already have an application managed by flux and am just adding the image automation piece.

I have not used it extensively and may be missing something here, but I was pretty stuck on this for a day.

Using the link [here](https://fluxcd.io/docs/guides/cron-job-image-auth/#using-cronjob-to-sync-ecr-credentials-as-a-kubernetes-secret) to configure the ECR authentication to enable sync against my image repo I was getting a 'ContainerCannotRun' error for the 'create-secret' container.  

I already set up my IAM role with the correct access as per the IRSA requirement and am using that in the cronjob so was sure it was not that.

When I describe the failed job, there is a failed message like `cannot stat '/bin/bash'`.  Thus the container is not even starting to be able to run its command to create the secret.

I tried running the flux-cli:v0.25.2 image locally trying to use and see that there is indeed no /bin/bash:

![Screenshot 2022-02-23 at 11 59 12](https://user-images.githubusercontent.com/43172431/155315333-504caa60-9f12-417f-b076-4e03d453b4d1.png)
 
Even if the flux-cli container did work, there is no kubectl command (I think).  

I swapped out the flux-cli image to a custom one I use that has kubectl installed and the secret got created and the scan of the repo worked just fine.

So it feels like:

1. The flux-cli image is not needed here or the secret creation command is incorrect
2. A kubectl image is needed
3. I am missing something...

Setup:

Flux v2
Kubernetes v1.19
flux-cli:v0.25.2

Thanks, J

**Comment by stefanprodan** [comment]
kubectl is included in the flux-cli image https://github.com/fluxcd/flux2/blob/main/Dockerfile, we need to change the command to `/bin/sh`

**Comment by js-johnpope** [comment]
Using a custom image with kubectl worked for me, the documented process did not.

**Comment by js-johnpope** [comment]
Re-opening.

The fix suggested by @morganchristiansson looks good?

**Comment by js-johnpope** [comment]
https://github.com/fluxcd/website/pull/846
