### ISSUE TITLE
Blog: RSS button overshadows deprecation notice

### ISSUE THREAD

**Issue by dholbach** [fluxcd/website#834]
On <https://fluxcd.io/blog/2021/03/march-2021-update/>:

![Bildschirmfoto von 2022-03-16 14-52-46](https://user-images.githubusercontent.com/1346979/158605552-9e9ad03f-df41-440b-a8a4-55c6be002a85.png)

@juozasg Do you think you can maybe help with this? :innocent:

**Comment by dholbach** [comment]
#832 introduced this.

**Comment by kingdonb** [comment]
<img width="1145" alt="Screen Shot 2022-03-16 at 11 07 27 AM" src="https://user-images.githubusercontent.com/3286998/158622348-5176f2e9-8a2c-4586-b38f-0fdd4b7ebccc.png">

This would be one way to fix it (added margin-right of 110px here)
