### ISSUE TITLE
GA roadmap: Incident management and troubleshooting guides

### ISSUE THREAD

**Issue by dholbach** [fluxcd/website#854]
From <https://fluxcd.io/roadmap/>

Let's discuss "Incident management and troubleshooting guides" - what do we want to add to our docs to be able to resolve this issue?

**Comment by dholbach** [comment]
I had a chat with @pjbgf about this and we came to the conclusion that starting with a "troubleshooting cheatsheet" could be a good start. The next step could be a more general doc, including a flow diagram, some more background info, etc 

does that make sense? here's a quick draft (needs more text still): https://docs.google.com/document/d/1FV4adriWQIH-0JZXeknZhKlPbxa8SibrRcX6SVhgOaQ/edit#

**Comment by makkes** [comment]
I like what's already in that doc. Thanks @dholbach. From my point of view we can just start with the items in there and extend the troubleshooting guide/runbook going forward.

**Comment by makkes** [comment]
We may want to move over some items from the FAQ, e.g. https://fluxcd.io/docs/faq/#how-do-i-resolve-webhook-does-not-support-dry-run-errors

**Comment by pjbgf** [comment]
The current documentation on this front suffices for GA, from now on it will be an on-going effort to keep it up to date and improve it.

Closing as per https://github.com/fluxcd/website/pull/1094#discussion_r956073759.
