### ISSUE TITLE
RSS feed for the blog

### ISSUE THREAD

**Issue by aholbreich** [fluxcd/website#88]
Hello everyone,

it would be nice to be able to subscribe to the blog (https://fluxcd.io/blog/) via any RSS/atom reader.
any plans for this?

**Comment by dholbach** [comment]
@aholbreich How's https://deploy-preview-89--fluxcd.netlify.app/blog/index.xml working for you?

**Comment by aholbreich** [comment]
@dholbach jepp, works with feedly.

**Comment by dholbach** [comment]
→ https://fluxcd.io/blog/index.xml
