### ISSUE TITLE
Fork the fluxcd/website repository limit

### ISSUE THREAD

**Issue by patrick-guy-rodies** [fluxcd/website#890]
Hey guys,

I am trying to add our company name and following https://github.com/fluxcd/website/blob/main/adopters#readme 
I get an error "No more forks can be created. [View existing forks.](https://github.com/fluxcd/website/network/members)"

Can you please help?

Thanks

**Comment by dholbach** [comment]
That's very strange. Maybe you have reached a limit of forks you created personally? We are currently on 149 forks, which is not a lot compared to other projects.

Maybe you can share a link to your company logo and its name and I'll go add it for you?

**Comment by dholbach** [comment]
Can be closed after #895 was merged now.
