### ISSUE TITLE
Fix misspelling in Flagger hero content - canaray

### ISSUE THREAD

**Issue by russomi** [fluxcd/website#94]
See [here](https://github.com/fluxcd/website/blob/32f8c2e8d08d458525dc3841114d02a221d133a0/config.toml#L274) misspelling error for canary.

incorrect: canaray
correct: canary

![image](https://user-images.githubusercontent.com/859824/107398336-852b9d00-6acd-11eb-9f62-1c949c483fa4.png)

**Comment by dholbach** [comment]
Thanks for letting us know, @russomi!
