### ISSUE TITLE
Updated landing page resources section

### ISSUE THREAD

**Issue by dholbach** [fluxcd/website#941]
Updated landing page resources section

https://fluxcd.io/resources has many new high quality videos - let's move some of them to the landing page.

CC @staceypotter - let's tag-team on this! :-)

**Comment by Santosh1176** [comment]
Hey @dholbach, I would love to work on this.

**Comment by dholbach** [comment]
That's great @Santosh1176

**Comment by staceypotter** [comment]
What about swapping out for these:
1. Flux in > 10 minutes (Saiyam Pathak): https://youtu.be/1X3JgCnRNsw  
2. Full GitOps Tutorial: Getting Started with Flux CD (Anaïs Urlichs): https://youtu.be/5u45lXmhgxA
3. The FASTEST way to deploy apps to Kubernetes (Techno Tim): https://youtu.be/PFLimPh5-wo
4. GitOps with GitHub Actions & Flux (Kingdon Barrett): https://youtu.be/cR2eCMbiZg4?t=298
5. GitOps for Helm Users (Scott Rigby): https://youtu.be/sQTkLT-V6sg
6. Flux at GitOpsCon EU 2022 Playlist: https://youtube.com/playlist?list=PLwjBY07V76p53FP85y03psCnb95u095Do
7. GitOps Days 2022 Playlist (a Flux fest): https://youtube.com/playlist?list=PL9lTuCFNLaD0NVkR17tno4X6BkxsbZZfr

**Comment by dholbach** [comment]
Thanks @staceypotter - that sounds great.

@Santosh1176 Would you still like to work on this?

**Comment by Santosh1176** [comment]
@dholbach Sorry for being inactive on the task. Yes, I would like to work on this and thanks for the list of resources. I’ll swap the current ones with those in the list.

**Comment by staceypotter** [comment]
Actually, I just noticed there should only be 6 resources, and I mistakenly added 7. @dholbach or @Santosh1176 do you have opinions on what should be left out/off?

**Comment by staceypotter** [comment]
@Santosh1176 - do you have a branch you could reference where I could suggest/commit? It's a bit hard to read the descriptions from the image....

**Comment by dholbach** [comment]
Yes, sounds good!
