### ISSUE TITLE
Ecosystem page: Add a section to add products/services that are built on top of Flux

### ISSUE THREAD

**Issue by dholbach** [fluxcd/website#947]
I think it'd be great to have a section on the ecosystem page to list products and services that are built on top of Flux.

Opinions?

**Comment by stefanprodan** [comment]
Yes big +1 from me. At KubeCon Valencia several vendors showcased how they use Flux in their products:
- VMware Tanzu
- Azure Arc
- Giant Swarm 
- Weaveworks Weave Gitops Enterprise 
- D2IQ

I think the list is longer, the once above had talks about this so it’s fine to list them.

**Comment by staceypotter** [comment]
Agreed! Perhaps we can encourage folks to add themselves to this section similarly to how they would add themselves as Adopters?
