### ISSUE TITLE
Resources: add missing Flux videos from KubeCon EU 2022

### ISSUE THREAD

**Issue by dholbach** [fluxcd/website#953]
Check out https://www.youtube.com/c/cloudnativefdn/videos?view=0&sort=dd&shelf_id=0 and add Flux sessions to https://fluxcd.io/resources

**Comment by staceypotter** [comment]
I can add GitOpsCon videos, as these are out. But KubeCon EU videos will not be posted for at least another week I think.

**Comment by Santosh1176** [comment]
@dholbach @staceypotter can I work on this?

**Comment by dholbach** [comment]
Yes, please. Sounds great!
