### ISSUE TITLE
Beautify blog section

### ISSUE THREAD

**Issue by dholbach** [fluxcd/website#96]
https://fluxcd.io/blog/ currently looks a bit bleak.

I think it could either 
 - show the full last 10 articles or
 - show the 10 last articles and their featured image ... if that can be accomplished easily(?)

**Comment by hiddeco** [comment]
I would not opt for option 1 due to SEO.

**Comment by dholbach** [comment]
> I would not opt for option 1 because of SEO (and content duplication).

WFM. I was maybe thinking of a Planet style page.

**Comment by hiddeco** [comment]
> Planet style page

I have no idea what this means

**Comment by dholbach** [comment]
e.g. https://planet.gnome.org/

**Comment by dholbach** [comment]
![Screenshot from 2021-04-14 15-47-21](https://user-images.githubusercontent.com/1346979/114720962-c001b980-9d38-11eb-8dad-cddd70879eee.png)
